[package]
name = "CSFs_loader"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
arrow = "57.1.0"
parquet = "57.1.0"
pyo3 = "0.27.2"
toml = "0.9.9"
serde = { version = "1.0.215", features = ["derive"] }
crossbeam-channel = "0.5.13"
num_cpus = "1.16.0"

[lib]
name = "csfs_loader"
crate-type = ["cdylib", "rlib", "staticlib"]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
