[workspace]
authors = ["YenochQin <yenochqin@hotmail.com>"]
channels = ["conda-forge"]
name = "rCSFs"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
rust = ">=1.92.0,<1.93"
maturin = ">=1.10.2,<2"
patchelf = ">=0.17.2"
python = ">=3.13,<3.14"
mypy = ">=1.19.1,<2"
ruff = ">=0.14.10,<0.15"
pip = ">=25.3,<26"
