[workspace]
authors = ["YenochQin <yenochqin@hotmail.com>"]
channels = ["conda-forge"]
name = "rCSFs"
platforms = ["linux-64",'win-64']
version = "1.0.0"

[tasks]

[dependencies]
rust = ">=1.85.0"
maturin = ">=1.10.2,<2"
python = ">=3.13,<3.14"
mypy = ">=1.19.1,<2"
ruff = ">=0.14.10,<0.15"
pip = ">=25.3,<26"

[target.linux-64.dependencies]
patchelf = ">=0.17.2"
